EmployeeManager.Mvc/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManager.Mvc.Models
{
    public class AppDbContext:DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options):base(options)
        {

        }

        public DbSet<Employee> Employees { get; set; }
        public DbSet<Country> Countries { get; set; }
    }
}

EmployeeManager.Mvc/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManager.Mvc.Models
{
    public class Country
    {
        public int CountryID { get; set; }
        public string Name { get; set; }
    }
}

EmployeeManager.Mvc/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace EmployeeManager.Mvc.Models
{
    [Table("Employees")]
    public class Employee
    {
        [Column("EmployeeID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required(ErrorMessage ="Employee ID is required")]
        [Display(Name = "Employee ID")]
        public int EmployeeID { get; set; }


        [Column("FirstName")]
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required")]
        [StringLength(10,ErrorMessage ="First Name must be less than 10 characters")]
        public string FirstName { get; set; }


        [Column("LastName")]
        [Display(Name = "Last Name")]
        [Required(ErrorMessage ="Last Name is required")]
        [StringLength(20,ErrorMessage ="Last Name must be less than 20 characters")]
        public string LastName { get; set; }


        [Column("Title")]
        [Display(Name = "Title")]
        [Required(ErrorMessage ="Title is required")]
        [StringLength(30,ErrorMessage ="Title must be less than 30 characters")]
        public string Title { get; set; }


        [Column("BirthDate")]
        [Display(Name = "Birth Date")]
        [Required(ErrorMessage ="Birth Date is required")]
        public DateTime BirthDate { get; set; }


        [Column("HireDate")]
        [Display(Name = "Hire Date")]
        [Required(ErrorMessage ="Hire Date is required")]
        public DateTime HireDate { get; set; }


        [Column("Country")]
        [Display(Name = "Country")]
        [Required(ErrorMessage ="Country is required")]
        [StringLength(15,ErrorMessage ="Country must be less than 15 characters")]
        public string Country { get; set; }


        [Column("Notes")]
        [Display(Name = "Notes")]
        [StringLength(500,ErrorMessage ="Notes must be less than 500 characters")]
        public string Notes { get; set; }
    }
}

EmployeeManager.Mvc/Models/ErrorViewModel.cs
using System;

namespace EmployeeManager.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeManager.Mvc/Models/Register.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;


namespace EmployeeManager.Mvc.Models
{
    public class Register
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [Compare("Password")]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }

        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Required]
        [Display(Name = "Birth Date")]
        public DateTime BirthDate { get; set; }
    }
}

EmployeeManager.Mvc/Models/SignIn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;


namespace EmployeeManager.Mvc.Models
{
    public class SignIn
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }
    }
}

EmployeeManager.Mvc/Controllers/EmployeeManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeManager.Mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeManager.Mvc.Controllers
{
    public class EmployeeManagerController : Controller
    {
        private AppDbContext db = null;
        public EmployeeManagerController(AppDbContext db)
        {
            this.db = db;
        }

        private void FillCountries()
        {
            try
            {
                List<SelectListItem> countries = (from c in db.Countries
                                                  orderby c.Name ascending
                                                  select new SelectListItem()
                                                  {
                                                      Text = c.Name,
                                                      Value = c.Name
                                                  }).ToList();
                ViewBag.Countries = countries;
            }
            catch(Exception ex)
            {

            }

        }

        public IActionResult List()
        {
            List<Employee> model = (from e in db.Employees
                                    orderby e.EmployeeID
                                    select e).ToList();
            return View(model);
        }

        public IActionResult Insert()
        {
            FillCountries();
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Employee model)
        {
            FillCountries();
            if (ModelState.IsValid)
            {
                db.Employees.Add(model);
                db.SaveChanges();
                ViewBag.Message = "Employee inserted successfully";
            }

            return View(model);
        }

        public IActionResult Update(int id)
        {
            FillCountries();
            Employee model = db.Employees.Find(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Employee model)
        {
            FillCountries();
            if (ModelState.IsValid)
            {
                db.Employees.Update(model);
                db.SaveChanges();
                ViewBag.Message = "Employee updated successfully";
            }

            return View(model);
        }
    }
}

EmployeeManager.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EmployeeManager.Mvc.Models;

namespace EmployeeManager.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeManager.Mvc/Views/EmployeeManager/Insert.cshtml
@model Employee

<h2>Insert New Employee</h2>
<h3 class="message">@ViewBag.Message</h3>
<form asp-controller="EmployeeManager" asp-action="Insert" method="post">
    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="FirstName"></label> :
            </td>
            <td>
                <input type="text" asp-for="FirstName" />
                <span asp-validation-for="FirstName" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="LastName"></label> :
            </td>
            <td>
                <input type="text" asp-for="LastName" />
                <span asp-validation-for="LastName" class="message"></span>

            </td>            
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Title"></label>:
            </td>
            <td>
                <input type="text" asp-for="Title" />
                <span asp-validation-for="Title" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="BirthDate"></label>
            </td>
            <td>
                <input type="date" asp-for="BirthDate" />
                <span asp-validation-for="BirthDate" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="HireDate"></label> :
            </td>
            <td>
                <input type="date" asp-for="HireDate" />
                <span asp-validation-for="HireDate" class="message"
></span>            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Country"></label>
            </td>
            <td>
                <select asp-for="Country" asp-items="@ViewBag.Countries">
                    <option value="">Please select</option>
                </select>
                <span asp-validation-for="Country" class="message"></span>
            </td>
        </tr>
        <tr>
            <td class="right">
                <label asp-for="Notes"></label>:
            </td>
            <td>
                <textarea asp-for="Notes" rows="5" cols="40"></textarea>
                <span asp-validation-for="Notes" class="message"></span>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>

    </table>
</form>

<br /><br />

<a asp-controller="EmployeeManager" asp-action="List">Back to Employee listeng</a>

EmployeeManager.Mvc/Views/EmployeeManager/List.cshtml
@model List<Employee>
<h2>List of Employees</h2>
<h2 class="message">@TempData["Message"]</h2>

<a asp-controller="EmployeeManager" asp-action="Insert" class="linkbutton">Insert</a>
<br /> <br />
<table border="1">
    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Title</th>
        <th colspan="2"> Actions</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.EmployeeID</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Title</td>
            <td>
                <a asp-controller="EmployeeManager"
                   asp-action="Update"
                   asp-route-id="@item.EmployeeID"
                   class="linkbutton">Update</a>
            </td>
            <td>
                <a asp-controller="EmployeeManager"
                   asp-action="Delete"
                   asp-route-id="@item.EmployeeID"
                   class="linkbutton">Delete</a>
            </td>
        </tr>
    }
</table>

EmployeeManager.Mvc/Views/EmployeeManager/Update.cshtml
@model Employee
<h2>Update existing employee</h2>
<h3 class="message">@ViewBag.Message</h3>
<form asp-controller="EmployeeManager" asp-action="Update"
      method="post">

    <table border="0">
        <tr>
            <td class="right">
                <label asp-for="EmployeeID">

                </label>:
            </td>
            <td>
                <input type="hidden" asp-for="EmployeeID" />
                <span>@Model.EmployeeID</span>
            </td>
        </tr>
    </table>

</form>

EmployeeManager.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeManager.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeManager.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeManager.Mvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EmployeeManager.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>